skinparam arrowThickness             1
skinparam sequence{
    LifeLineBorderColor        #4672C4
    ParticipantBorderColor     #C8C8C8
    boxBorderColor             #9BAAC7
    
    ' boxBorderThickness         5
    
    boxBackgroundColor         #F5F5F5
    
    ArrowColor                 #4672C4

    LifeLInebackgroundColor    #4672C4

    ParticipantBackgroundColor #4672C4

    GroupBorderThickness       1
    GroupBorderColor           #9BAAC7
}

skinparam Object{
    BackgroundColor #4672C4
    BorderColor     #263479
    FontStyle       bold
    FontSize        18
    AttributeFontSize 14
}

' skinparam NoteShadowing              true
skinparam DatabaseBorderColor        #263479
skinparam DatabaseBackgroundColor    #4672C4
skinparam ParticipantPadding         5
skinparam ParticipantBorderThickness 1
skinparam Shadowing                  false
skinparam BoxPadding                 10
skinparam roundcorner                0
skinparam backgroundColor            white 
